version: 2.1

jobs: 
  build: 
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: echo "hello world!"


workflows:
  verify: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - build

